### ISSUE TITLE
AppletonAPI version bump for new /search parameters

### ISSUE THREAD

**Issue by mikeputnam** [dhmncivichacks/civic-hack-api-locator#2]
Hi!

I've added a new/next version of the AppletonAPI where the /search parameters are no longer separate house_num and street_name.  They've been combined into a single "q" parameter.

[Here is the commit that documents the change.](https://github.com/mikeputnam/appletonapi/commit/17bd30de8222d99a2960f1ca6a05ff19dc387213) 

Not sure how this affects your contract versioning stuff.

I'm still serving the previous API as well as the newer one:
`2-2.appletonapi.appspot.com`
`3-0.appletonapi.appspot.com`

Mike Putnam

**Comment by mrosack** [comment]
Cool - I need to get back to working on it this weekend, I'll update the mock data.  I'm not too concerned with it right now, I figure once Christian or I makes some progress on an API for another city we can put our heads together on a common data contract.

**Comment by mrosack** [comment]
I think I can close this since we already integrated appletonapi with the common contract.
