### ISSUE TITLE
implementations error message

### ISSUE THREAD

**Issue by chrisjaure** [dhmncivichacks/civic-hack-api-locator#3]
It wold be nice it the implementations endpoint returned an error if the address doesn't contain a zip code so I can fix this issue in the web client :)

https://github.com/dhmncivichacks/isitrecyclingweek-web/issues/13

Right now it returns an empty array if there are no implementations or if the address is invalid. I need to be able to differentiate between the two.

**Comment by mrosack** [comment]
Any thoughts on how I should return this error?  I'm thinking a 400 response with the message "Address Invalid".  Do you care, @mikeputnam?

**Comment by chrisjaure** [comment]
400 response with a message sounds good to me.

**Comment by mikeputnam** [comment]
Same here; no qualms.

**Comment by mrosack** [comment]
closed via pull request #5
