### ISSUE TITLE
Return https urls

### ISSUE THREAD

**Issue by chrisjaure** [dhmncivichacks/civic-hack-api-locator#7]
I've got an issue over here https://github.com/dhmncivichacks/isitrecyclingweek-web/issues/14 for the web app.

Basically, I need to run everything over `https` in order to support geolocation. This api returns `http` urls only.

**Comment by mikeputnam** [comment]
As the locator returns the local api's endpoint, this requirement could extend to all municipalities.

**Comment by mikeputnam** [comment]
Maybe time to try out Let's Encrypt!

**Comment by chrisjaure** [comment]
I tried a couple api endpoints (I suppose they were both hosted on Azure) and they support HTTPS already. Do you know if yours does on Google, @mikeputnam?

**Comment by mikeputnam** [comment]
Apparently so!  Hooray for wildcard certificates!

![image](https://cloud.githubusercontent.com/assets/213371/14772791/ba27d738-0a67-11e6-8a5f-dcc020edc2d8.png)

**Comment by mrosack** [comment]
fixed in b5c97bd - sorry i lost track of this one!
